trigger:
  branches:
    include:
      - main  # ou o branch principal do seu repo

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.5.7'  # ou a versão que você estiver usando

steps:
  - checkout: self

  - task: UseTerraform@0
    inputs:
      terraformVersion: '$(TF_VERSION)' 

  - script: |
      terraform -version
    displayName: 'Verificar versão do Terraform'

  - script: |
      echo "Conexão com GitHub e execução da pipeline funcionando!"
    displayName: 'Mensagem de sucesso'
